# Generated by Django 3.2.21 on 2023-09-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='frame',
            field=models.CharField(blank=True, choices=[('no_frame', 'No Frame'), ('standard_frame', 'Standard Frame'), ('premium_frame', 'Premium Frame')], max_length=20, null=True),
        ),
    ]
