# Generated by Django 3.2.21 on 2023-09-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_auto_20230912_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='painting',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='paintings.SubCategory'),
        ),
    ]
